export const CREATE_MATCH_SUBMIT = 'CREATE_MATCH_SUBMIT';
export const CREATE_MATCH_SUCCESS = 'CREATE_MATCH_SUCCESS';
export const CREATE_MATCH_ERROR = 'CREATE_MATCH_ERROR';
export const CREATE_MATCH_CLEAR = 'CREATE_MATCH_CLEAR';

export const DO_COMPLETE_MATCH = 'DO_COMPLETE_MATCH';
export const DO_COMPLETE_MATCH_SUCCESS = 'DO_COMPLETE_MATCH_SUCCESS';
export const DO_COMPLETE_MATCH_ERROR = 'DO_COMPLETE_MATCH_ERROR';
export const MATCH_DETAILS_ERROR_CLEAR = 'MATCH_DETAILS_ERROR_CLEAR';
export const MATCH_DETAILS_SUCCESS_CLEAR = 'MATCH_DETAILS_SUCCESS_CLEAR';

export const SELECT_HOLE = 'SELECT_HOLE';
export const SET_MATCH_ID = 'SET_MATCH_ID';
export const ADD_HOLE_TO_MATCH = 'ADD_HOLE_TO_MATCH';
export const ADD_COURSE_TO_MATCH = 'ADD_COURSE_TO_MATCH';
export const UPDATE_MATCH = 'UPDATE_MATCH';
export const GET_MATCHES = 'GET_MATCHES';

export const MATCHES_ADD = 'MATCHES_ADD';
export const MATCHES_FETCH = 'MATCHES_FETCH';
export const MATCHES_FETCH_ERROR = 'MATCHES_FETCH_ERROR';

export const STORE_DB_SYNC = 'STORE_DB_SYNC';
export const PATCH_SCORE_UPDATE = 'PATCH_SCORE_UPDATE';
export const PATCH_SCORE_UPDATE_SUCCESS = 'PATCH_SCORE_UPDATE_SUCCESS';
export const PATCH_SCORE_UPDATE_ERROR = 'PATCH_SCORE_UPDATE_ERROR';
export const PATCH_SCORE_UPDATE_ERROR_CLEAR = 'PATCH_SCORE_UPDATE_ERROR_CLEAR';
export const PATCH_SCORE_UPDATE_SUCCESS_CLEAR =
  'PATCH_SCORE_UPDATE_SUCCESS_CLEAR';

export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';
export const POST_LOGIN_ERROR_CLEAR = 'POST_LOGIN_ERROR_CLEAR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGOUT_ERROR_CLEAR = 'LOGOUT_ERROR_CLEAR';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
