export const CREATE_MATCH_SUBMIT = 'CREATE_MATCH_SUBMIT';
export const CREATE_MATCH_SUCCESS = 'CREATE_MATCH_SUCCESS';
export const CREATE_MATCH_ERROR = 'CREATE_MATCH_ERROR';
export const CREATE_MATCH_CLEAR = 'CREATE_MATCH_CLEAR';

export const DO_COMPLETE_MATCH = 'DO_COMPLETE_MATCH';

export const SELECT_HOLE = 'SELECT_HOLE';
export const SET_MATCH_ID = 'SET_MATCH_ID';
export const ADD_HOLE_TO_MATCH = 'ADD_HOLE_TO_MATCH';
export const ADD_COURSE_TO_MATCH = 'ADD_COURSE_TO_MATCH';
export const UPDATE_MATCH = 'UPDATE_MATCH';
export const GET_MATCHES = 'GET_MATCHES';

export const MATCHES_ADD = 'MATCHES_ADD';
export const MATCHES_FETCH = 'MATCHES_FETCH';
export const MATCHES_FETCH_ERROR = 'MATCHES_FETCH_ERROR';

export const STORE_DB_SYNC = 'STORE_DB_SYNC';
export const PATCH_SCORE_UPDATE = 'PATCH_SCORE_UPDATE';
export const PATCH_SCORE_UPDATE_SUCCESS = 'PATCH_SCORE_UPDATE_SUCCESS';
export const PATCH_SCORE_UPDATE_ERROR = 'PATCH_SCORE_UPDATE_ERROR';
export const PATCH_SCORE_UPDATE_ERROR_CLEAR = 'PATCH_SCORE_UPDATE_ERROR_CLEAR';
export const PATCH_SCORE_UPDATE_SUCCESS_CLEAR =
  'PATCH_SCORE_UPDATE_SUCCESS_CLEAR';
