const matches = [
  {
    id: '1',
    course: {
      name: 'Bidwell Golf Course',
      location: 'Chico, CA',
      par: 72,
      holes: 18
    },
    date: new Date(2018, 5, 8),
    holes: [
      { id: '1', par: 4, score: 5 },
      { id: '2', par: 3, score: 3 },
      { id: '3', par: 4, score: 5 },
      { id: '4', par: 3, score: 4 },
      { id: '5', par: 5, score: 6 },
      { id: '6', par: 4, score: 5 },
      { id: '7', par: 3, score: 4 },
      { id: '8', par: 5, score: 5 },
      { id: '9', par: 5, score: 4 },
      { id: '10', par: 4, score: 5 },
      { id: '11', par: 5, score: 5 },
      { id: '12', par: 3, score: 4 },
      { id: '13', par: 4, score: 5 },
      { id: '14', par: 4, score: 6 },
      { id: '15', par: 4, score: 5 },
      { id: '16', par: 3, score: 4 },
      { id: '17', par: 4, score: 4 },
      { id: '18', par: 5, score: 6 },
    ],
  },
  {
    id: '2',
    course: {
      name: 'Golden Gate Golf Course',
      location: 'San Francisco, CA',
      par: 72,
      holes: 18
    },
    date: new Date(2018, 4, 28),
    holes: [
      { id: '1', par: 4, score: 5 },
      { id: '2', par: 3, score: 3 },
      { id: '3', par: 4, score: 4 },
      { id: '4', par: 3, score: 4 },
      { id: '5', par: 5, score: 5 },
      { id: '6', par: 4, score: 5 },
      { id: '7', par: 3, score: 4 },
      { id: '8', par: 5, score: 5 },
      { id: '9', par: 5, score: 4 },
      { id: '10', par: 4, score: 5 },
      { id: '11', par: 5, score: 5 },
      { id: '12', par: 3, score: 3 },
      { id: '13', par: 4, score: 5 },
      { id: '14', par: 4, score: 6 },
      { id: '15', par: 4, score: 5 },
      { id: '16', par: 3, score: 3 },
      { id: '17', par: 4, score: 4 },
      { id: '18', par: 5, score: 6 },
    ],
  },
  {
    id: '3',
    course: {
      name: 'Bidwell Golf Course',
      location: 'Chico, CA',
      par: 72,
      holes: 18
    },
    date: new Date(2018, 4, 12),
    holes: [
      { id: '1', par: 4, score: 5 },
      { id: '2', par: 3, score: 3 },
      { id: '3', par: 4, score: 5 },
      { id: '4', par: 3, score: 4 },
      { id: '5', par: 5, score: 6 },
      { id: '6', par: 4, score: 6 },
      { id: '7', par: 3, score: 4 },
      { id: '8', par: 5, score: 5 },
      { id: '9', par: 5, score: 4 },
      { id: '10', par: 4, score: 5 },
      { id: '11', par: 5, score: 5 },
      { id: '12', par: 3, score: 5 },
      { id: '13', par: 4, score: 5 },
      { id: '14', par: 4, score: 6 },
      { id: '15', par: 4, score: 5 },
      { id: '16', par: 3, score: 4 },
      { id: '17', par: 4, score: 4 },
      { id: '18', par: 5, score: 6 },
    ],
  },
  {
    id: '3',
    course: {
      name: 'TPC Harding',
      location: 'San Francisco, CA',
      par: 72,
      holes: 18
    },
    date: new Date(2018, 4, 12),
    holes: [
      { id: '1', par: 4, score: 4 },
      { id: '2', par: 3, score: 3 },
      { id: '3', par: 4, score: 4 },
      { id: '4', par: 3, score: 2 },
      { id: '5', par: 5, score: 4 },
      { id: '6', par: 4, score: 4 },
      { id: '7', par: 3, score: 3 },
      { id: '8', par: 5, score: 5 },
      { id: '9', par: 5, score: 6 },
      { id: '10', par: 4, score: 3 },
      { id: '11', par: 5, score: 4 },
      { id: '12', par: 3, score: 3 },
      { id: '13', par: 4, score: 4 },
      { id: '14', par: 4, score: 5 },
      { id: '15', par: 4, score: 3 },
      { id: '16', par: 3, score: 3 },
      { id: '17', par: 4, score: 3 },
      { id: '18', par: 5, score: 4 },
    ],
  }
];

export { matches };